name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
      options: --user user

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build APK
      run: |
        buildozer --warn_on_root=0 android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: bin/*.apk
